export enum ErrorCode {
  DUPLICATE_SAVE = 'DUPLICATE_SAVE',
  UNAVAILABLE_IN_COUNTRY = 'UNAVAILABLE_IN_COUNTRY',
  NOT_SAVED = 'NOT_SAVED',
  NOT_FOUND = 'NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  AUTH_INVALID = 'AUTH_INVALID',
  INTERNAL = 'INTERNAL_SERVER_ERROR',
}
